#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          on             \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    active_window_border_color   0xff008bff     \
    normal_window_border_color   0x01000000     \
    window_border                off            \
    split_ratio                  0.50           \
    auto_balance                 off            \
    top_padding                  8              \
    bottom_padding               8              \
    left_padding                 8              \
    right_padding                8              \
    window_gap                   8              \
    layout                       bsp            \

yabai -m rule --add app="iTerm2" space=^1
yabai -m rule --add app="kitty" space=^1

yabai -m rule --add app="Brave" space=^2

yabai -m rule --add app="GoLand" space=^3
yabai -m rule --add app="GoLand" title="Preferences" space=^3 manage=off

yabai -m rule --add app="WebStorm" space=^4
yabai -m rule --add app="WebStorm" title="Preferences" space=^4 manage=off

echo "yabai configuration loaded.."
