[[block]]
block = "music"
format = "   {$combo.str(max_w:40,rot_interval:0.5) |}"

[[block]]
block = "backlight"
format = "   $brightness "

[[block]]
block = "battery"

[[block]]
block = "net"
format = "   {$signal_strength$frequency|Wired connection} "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $used -$total "

[[block]]
block = "memory"
format = " $icon $mem_used.eng - $mem_total.eng "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %v %r') "
